server:
  error:
    include-message: always
  port: 8078
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8074/realms/DanielTenkorang
          jwk-set-uri: ${spring.security.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  datasource:
    password: admin123
    url: jdbc:postgresql://localhost:5433/keycloaksecdb
    username: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  jwt:
    auth:
      converter:
        resource-id: kwame-rest-api
        principal-attribute: preferred_username