server:
  error:
    include-message: always
  port: 8020
spring:
  datasource:
    password: admin123
    url: jdbc:postgresql://localhost:5433/teacodescdb
    username: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false